host: localhost:8085
info:
  contact: {}
  description: API Gateway of Authorazation
  title: User
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
